### ISSUE TITLE
Lists are not displayed correctly 

### ISSUE THREAD

**Issue by aboueleyes** [mohamedelhefni/qalam#2]
![image](https://user-images.githubusercontent.com/35760882/234099329-342127bb-470e-434b-8560-ec560400cb47.png)

**Comment by aboueleyes** [comment]
[Screencast from 04-24-2023 09:44:44 PM.webm](https://user-images.githubusercontent.com/35760882/234099920-f8199814-4a31-48b4-b554-87d8f5faa426.webm)

**Comment by mohamedelhefni** [comment]
fixed!
